### PR TITLE
[Fix] fix initialization of ref_llm for full param dpo training with zero-3

### PR DESCRIPTION
**Pull request by xu-song**
`ref_llm` can not be instantiated while full param dpo training  with zero-3.

This pull request enable instantiation of ref_llm with the following config.

```py
model = dict(
    type=DPO,
    loss_type=dpo_loss_type,
    use_varlen_attn=use_varlen_attn,
    beta=loss_beta,
    label_smoothing=label_smoothing,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        ),
    ref_llm=dict(  ##### initialization of ref_llm #######
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        ),
    )
```

### CODE REVIEW

**Comment by RangiLyu** [comment]
Thank you for your contribution! It appears that this fix might not fully address the issue when using var_len_attention. I noticed another solution in PR #781, which seems to be a more comprehensive approach.

**Comment by xu-song** [comment]
Create another SupervisedFinetune instance is not recommended.

**Comment by pppppM** [comment]
@xu-song Great PR! There are conflicts that need to be resolved.

**Comment by xu-song** [comment]
conflicts has been resolved

**Review by HIT-cwh — APPROVED** [review]

**Pull request merged**
