### PR TITLE
[Feature] add yi-6b and yi-34b sft script

### PR DESCRIPTION
**Pull request by amulil**

### CODE REVIEW

**Comment by LZHgrla** [comment]
Thanks very much for your contribution!

I have reviewed this PR and there are two comments:
1. Please set `accumulative_counts=16` and `dataloader_num_workers=0` to align with other configs
2. Use `PagedAdamW32bit` instead of `AdamW` is better?

**Comment by amulil** [comment]
> Thanks very much for your contribution!
> 
> I have reviewed this PR and there are two comments:
> 
> 1. Please set `accumulative_counts=16` and `dataloader_num_workers=0` to align with other configs
> 2. Use `PagedAdamW32bit` instead of `AdamW` is better?

Thanks for your advice.I update them.

**Comment by LZHgrla** [comment]
@amulil 
Please fix the pre-commit~
Guide: https://github.com/InternLM/xtuner/blob/main/.github/CONTRIBUTING.md#2-configure-pre-commit

**Comment by amulil** [comment]
> @amulil Please fix the pre-commit~ Guide: https://github.com/InternLM/xtuner/blob/main/.github/CONTRIBUTING.md#2-configure-pre-commit

I'm sorry.It seems I have fixed it.Please check it. @LZHgrla

**Review by LZHgrla — APPROVED** [review]
@amulil 
LGTM!
Is this PR ready to be merged?

**Comment by amulil** [comment]
> LGTM!



> @amulil LGTM! Is this PR ready to be merged?

Yes!It can be merged. @LZHgrla

**Pull request merged**
